// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADo074PsqYBfP9n0-vdqPtaCj2tt_fYjc',
    appId: '1:903746756158:web:2f17a48d92ff0347c3fb6f',
    messagingSenderId: '903746756158',
    projectId: 'moenybalance',
    authDomain: 'moenybalance.firebaseapp.com',
    storageBucket: 'moenybalance.appspot.com',
    measurementId: 'G-3FTN22PQNC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqikRudQArRy2fnFWCUQEmOwd03U4kh28',
    appId: '1:903746756158:android:967d5a9f2b795048c3fb6f',
    messagingSenderId: '903746756158',
    projectId: 'moenybalance',
    storageBucket: 'moenybalance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChasAuXnKGPjpSJY_Y00sqHwwuGhfNeKM',
    appId: '1:903746756158:ios:6fb082ae8617d1d5c3fb6f',
    messagingSenderId: '903746756158',
    projectId: 'moenybalance',
    storageBucket: 'moenybalance.appspot.com',
    iosBundleId: 'com.example.moneybalance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChasAuXnKGPjpSJY_Y00sqHwwuGhfNeKM',
    appId: '1:903746756158:ios:6fb082ae8617d1d5c3fb6f',
    messagingSenderId: '903746756158',
    projectId: 'moenybalance',
    storageBucket: 'moenybalance.appspot.com',
    iosBundleId: 'com.example.moneybalance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADo074PsqYBfP9n0-vdqPtaCj2tt_fYjc',
    appId: '1:903746756158:web:ea05ff7d5f01bb1ac3fb6f',
    messagingSenderId: '903746756158',
    projectId: 'moenybalance',
    authDomain: 'moenybalance.firebaseapp.com',
    storageBucket: 'moenybalance.appspot.com',
    measurementId: 'G-6THYG4HP53',
  );
}
